sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t adilsaeed31/adilworld  .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push adilsaeed31/adilworld
