sudo: required

services:
  - docker

before_install:
  - docker build -t adilsaeed31/adilworld -f Dockerfile .

script:
  - docker run adilsaeed31/adilworld yarn start

after_success:
  - docker build -t adilsaeed31/adilworld .
